In [65]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [66]:
# training layer/ independent layer
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

# dependent layer
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [67]:
one_hot('amazing restaurant',30)

[8, 15]

In [68]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[5, 45],
 [29, 36],
 [20, 19],
 [39, 18, 40],
 [4, 37, 23],
 [6, 45],
 [1, 37, 20],
 [24, 49],
 [24, 5],
 [1, 16]]

In [69]:
maxLength = max(len(x) for x in encoded_reviews)
maxLength

3

In [70]:
# Now take
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 5 45  0  0]
 [29 36  0  0]
 [20 19  0  0]
 [39 18 40  0]
 [ 4 37 23  0]
 [ 6 45  0  0]
 [ 1 37 20  0]
 [24 49  0  0]
 [24  5  0  0]
 [ 1 16  0  0]]


In [71]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [72]:
X = padded_reviews
Y = sentiment

In [73]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              250       
                                                                 
 flatten_4 (Flatten)         (None, 20)                0         
                                                                 
 dense_4 (Dense)             (None, 1)                 21        
                                                                 
Total params: 271
Trainable params: 271
Non-trainable params: 0
_________________________________________________________________
None


In [74]:
model.fit(X, Y, epochs=50, verbose=0)

In [75]:
# evaluate the model
loss, accuracy = model.evaluate(X, Y)
accuracy

1/1 [==============================] - 0s 109ms/step - loss: 0.6197 - accuracy: 1.0000


1.0

In [76]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[-0.03334669,  0.08083764, -0.04401454, -0.00787273, -0.00175417],
       [-0.01495015, -0.0182014 , -0.01138056,  0.04852994,  0.0110864 ],
       [-0.03317164,  0.00699681, -0.04783697,  0.01373235, -0.0484415 ],
       [-0.04734545,  0.00035568, -0.02649143, -0.00249658,  0.01949873],
       [ 0.00344527,  0.03461237,  0.04400227, -0.09139546, -0.05717463],
       [ 0.0764999 , -0.05684622, -0.07064783, -0.02936162, -0.08322364],
       [-0.05238841, -0.02041394, -0.06849479,  0.07209994,  0.01959353],
       [ 0.04059272,  0.00410591,  0.04094917,  0.0480773 ,  0.03684534],
       [ 0.03530169,  0.04022438, -0.04082637, -0.02340404, -0.03582893],
       [ 0.04044913,  0.03308884, -0.01540088,  0.04127982, -0.01435655],
       [-0.04210956,  0.04594542,  0.00511367, -0.02802756,  0.04125304],
       [ 0.01707539,  0.03132043, -0.00244627, -0.01411282, -0.01781969],
       [ 0.0269275 ,  0.03767976, -0.02106086, -0.00025791, -0.02215268],
       [-0.0293664 ,  0.02508679,  0.0

In [77]:
len(weights)

50

In [79]:
weights[45]

array([-0.00252226,  0.013743  ,  0.03439075,  0.04786191, -0.02057177],
      dtype=float32)